### ISSUE TITLE
Meta: let's stop using discussions

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#3463]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

GitHub discussions just suck, they aren't searched when searching issues. They cannot be easily marked as resolved, maybe with a title change? There is no issue template for them. Webhooks for them are the most scuffed thing I've seen GitHub make in a good while. Want to get Discord notifications of discussions: lol no. They are like Twitch's Uservoice no one ever actually looks at them because they're  so bad to use. 

IMO we should move the suggestions into issues (probably with a clever issue form) ~~or a dedicated repo if that's not doable.~~ see ALazyMeme's comment below 

### Screenshots

n/a

### OS and Chatterino Version

commit 79db02aa66648b3f8be27f2bc54f581f4fb129b8 running on all the frustration discussions have caused me

**Comment by ALazyMeme** [comment]
I'm split with the dedicated repo. I think it's a good idea, but I feel like it'd be ignored (quite literally turning into Twitch UserVoice).

**Comment by romeogiggletoes** [comment]
To add to what has already been mentioned, some suggestions get left as issues anyway currently. #3316 #3250 #3109 #3104 #2938 #2916 #2885 #2878 #2843 #2810 #2731 #2723 #2690 etc. While I have limited understanding of GitHub, I don't see a point in not moving suggestions into issues. There will always be many open issues with a project this big, so 'cluttering' the issues tab should not be a worry, especially if the user base grows continually.

**Comment by Felanbird** [comment]
> currently.

Only 2 of these these suggestions are from after the change to discussions

**Comment by karl-police** [comment]
Doesn't Github give an option to disable it?

**Comment by ALazyMeme** [comment]
> Doesn't Github give an option to disable it?

Yes

**Comment by Mm2PL** [comment]
Closing this as we've managed to a lot of the problems i brought up in this post. We've managed to make them usable.
